// <auto-generated />
using System;
using BoardGamesLibrary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoardGamesLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200708184809_CreateDataBase")]
    partial class CreateDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("BoardGamesLibrary.Models.BoardGame", b =>
                {
                    b.Property<int>("IdGame")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<int>("NPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("IdGame");

                    b.ToTable("BoardGame");
                });

            modelBuilder.Entity("BoardGamesLibrary.Models.Match", b =>
                {
                    b.Property<int>("IdMatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<string>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdGameRef")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Winner")
                        .HasColumnType("TEXT");

                    b.HasKey("IdMatch");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("BoardGamesLibrary.Models.MatchRELPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMatchRef")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameRef")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Winner")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MatchRELPlayer");
                });

            modelBuilder.Entity("BoardGamesLibrary.Models.Player", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("WonMatches")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
